# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0012_auto_20160213_0930'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoritePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_profile', models.URLField()),
                ('twitter_profile', models.URLField()),
                ('linkedin_profile', models.URLField()),
                ('location', models.CharField(max_length=64)),
                ('reputation', models.IntegerField(default=0)),
                ('last_seen_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_activity_ip', models.GenericIPAddressField(null=True)),
                ('profile_views', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritepart',
            unique_together=set([('user', 'part')]),
        ),
    ]
