# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companyaltname',
            options={'ordering': ('company',), 'verbose_name': 'Alternate Company Name'},
        ),
    ]
